### ISSUE TITLE
 no auth mechanism defined

### ISSUE THREAD

**Issue by Chakhalyan1** [paOol/Bitcoin-Cash-RPC#5]
I have started Bitcoin Unlimited full node for bitcoin cash in my server, and i have use Bitcoin-Cash-RPC for connect via rpc. I have getting following error
`Unhandled rejection Error: no auth mechanism defined
    at Auth.onRequest (/root/BtcCash/node_modules/request/lib/auth.js:132:32)
    at Request.auth (/root/BtcCash/node_modules/request/request.js:1349:14)
    at Request.init (/root/BtcCash/node_modules/request/request.js:375:10)
    at new Request (/root/BtcCash/node_modules/request/request.js:128:8)
    at request (/root/BtcCash/node_modules/request/index.js:53:10)
    at /root/BtcCash/node_modules/request/index.js:61:12
    at Object.apply (/root/BtcCash/node_modules/@uphold/request-logger/src/index.js:27:19)
    at Function.post (/root/BtcCash/node_modules/request/index.js:100:12)
    at Function.tryCatcher (/root/BtcCash/node_modules/bluebird/js/release/util.js:16:23)
    at Function.ret [as postAsync] (eval at makeNodePromisifiedEval (/root/BtcCash/node_modules/bluebird/js/release/promisify.js:184:12), <anonymous>:14:23)
    at _bluebird.default.try (/root/BtcCash/node_modules/bitcoin-core/dist/src/index.js:168:27)
    at tryCatcher (/root/BtcCash/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.attempt.Promise.try (/root/BtcCash/node_modules/bluebird/js/release/method.js:39:29)
    at Client.command (/root/BtcCash/node_modules/bitcoin-core/dist/src/index.js:154:33)
    at apply (/root/BtcCash/node_modules/lodash/lodash.js:495:27)
    at Client.wrapper [as getInfo] (/root/BtcCash/node_modules/lodash/lodash.js:5356:16)
`

**Comment by knoxcard** [comment]
Did you set up your bitcoin.conf file?

**Comment by chakhalyan1** [comment]
no, its did not work

**Comment by knoxcard** [comment]
in linux command line...
find / -name "bitcoin.conf"

once you find the file ...
nano bitcoin.conf

server=1
rpcuser=bitcoinrpc
rpcpassword=FthX6VtgimHx2kLF1LWPo4EDhiMgCWmcu5Vu7vBLzuer
rpcport=8332
prune=2000

**Comment by chakhalyan1** [comment]
its not help for work bitcore-node
